const fs = require("fs");
const path = require("path");

/**
 * Load keywords generated by keywords.js
 */
function loadKeywords() {
  const data = fs.readFileSync("./output/keywords.json", "utf-8");
  return JSON.parse(data).keywords;
}

/**
 * Basic SEO page template
 */
function buildPage(keyword) {
  const title = keyword.charAt(0).toUpperCase() + keyword.slice(1);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <meta name="description" content="Information about ${keyword}. Compare options and learn how it works.">
</head>

<body>

  <header>
    <h1>${title}</h1>
  </header>

  <main>
    <section>
      <p>
        This page provides general information about <strong>${keyword}</strong>.
        Learn how options work, what to consider, and how eligibility is determined.
      </p>
    </section>

    <section>
      <h2>Things to Know</h2>
      <ul>
        <li>Requirements may vary by provider</li>
        <li>Approval depends on credit and income factors</li>
        <li>Terms differ by lender and location</li>
      </ul>
    </section>

    <section>
      <h2>Next Steps</h2>
      <p>
        Compare available options carefully before applying.
      </p>
    </section>
  </main>

  <footer>
    <p>Educational content only. Not a lender.</p>
  </footer>

</body>
</html>`;
}

/**
 * Save one HTML page per keyword
 */
function savePages(keywords) {
  const outputDir = "./output/pages";

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  keywords.forEach((keyword, index) => {
    const slug = keyword.replace(/\s+/g, "-").toLowerCase();
    const filePath = path.join(outputDir, `${slug}.html`);

    const html = buildPage(keyword);

    fs.writeFileSync(filePath, html);
  });

  console.log(`Generated ${keywords.length} pages in /output/pages`);
}

/**
 * Run generator
 */
function run() {
  const keywords = loadKeywords();
  savePages(keywords);
}

if (require.main === module) {
  run();
}

module.exports = {
  run
};
