const fs = require("fs");
const path = require("path");

/**
 * Load keywords generated by keywords.js
 */
function loadKeywords() {
  const filePath = path.join(__dirname, "../output/keywords.json");

  if (!fs.existsSync(filePath)) {
    throw new Error("keywords.json not found. Run engine/keywords.js first.");
  }

  const data = fs.readFileSync(filePath, "utf-8");
  return JSON.parse(data).keywords;
}

/**
 * Create SEO-safe slug
 */
function slugify(text) {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");
}

/**
 * HTML template generator
 */
function buildPage(keyword) {
  const title = keyword.charAt(0).toUpperCase() + keyword.slice(1);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <meta name="description" content="Learn about ${keyword}. Compare options and understand key factors before applying.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

<header>
  <h1>${title}</h1>
</header>

<main>

  <section>
    <p>
      This page is an informational overview of <strong>${keyword}</strong>.
      It explains general considerations, eligibility factors, and how comparisons typically work.
    </p>
  </section>

  <section>
    <h2>Key Points</h2>
    <ul>
      <li>Terms and conditions vary by provider</li>
      <li>Approval depends on financial profile</li>
      <li>Always compare multiple options before applying</li>
    </ul>
  </section>

  <section>
    <h2>Important Considerations</h2>
    <p>
      Make sure you understand repayment terms, fees, and total cost before making any financial decision.
    </p>
  </section>

</main>

<footer>
  <p>Educational content only. Not a lender or financial institution.</p>
</footer>

</body>
</html>`;
}

/**
 * Save all pages
 */
function savePages(keywords) {
  const outputDir = path.join(__dirname, "../output/pages");

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  let count = 0;

  for (const keyword of keywords) {
    const slug = slugify(keyword);
    const filePath = path.join(outputDir, `${slug}.html`);

    const html = buildPage(keyword);

    fs.writeFileSync(filePath, html);
    count++;
  }

  console.log(`Generated ${count} pages → output/pages/`);
}

/**
 * Run generator
 */
function run() {
  const keywords = loadKeywords();
  savePages(keywords);
}

if (require.main === module) {
  run();
}

module.exports = {
  run
};
